{{- if .Values.serviceAccount.create -}}

# create role 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: {{ .Values.serviceAccount.roleName }}
 namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "services", "configmaps"]
    verbs: ["get", "watch", "list"]   
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inward-rmt-service.serviceAccountName" . }}
  labels:
    {{- include "inward-rmt-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
---
# binding role to service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: {{ .Values.serviceAccount.roleName }}_{{ include "inward-rmt-service.serviceAccountName" . }}
 namespace: {{ .Release.Namespace }}
roleRef:
 kind: ClusterRole
 name: {{ .Values.serviceAccount.roleName }}
 apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: {{ include "inward-rmt-service.serviceAccountName" . }}
   namespace: {{ .Release.Namespace }}
  
{{- end }}
