efk:
  fluentd:
    host: "10.5.0.17"
    port: 24224

integration:
  # 0=api, 1=asyncQ, 2=syncQ, 
  adapter-type: 0
  int9013:
    #url: http://localhost:9090/integration/api/ivr9013
    url: http://localhost:7070/integration/bridge/ivr9013
    channel: int9013ReqQueue
  int9014:
    #url: http://localhost:9090/integration/api/ivr9014
    url: http://localhost:7070/integration/bridge/ivr9013
    channel: int9014ReqQueue 